### ISSUE TITLE
Crash on exit in destructor of CDROM_Interface_Image

### ISSUE THREAD

**Issue by dreamer** [dreamer/dosbox-staging#112]
I was testing some other feature and noticed that Warcraft 1 (GOG version) started crashing on exit for me. I did bisect and some preliminary investigation:

Crash was introduced in eaeb001b1709ea88d51179a53423fffdfdc81c37 (somehow I missed it in review :( ).

## Reproduction steps

GOG version of Warcraft 1 mounts CD image this way: `imgmount D "../WAR1.CUE" -t iso`; content of the .cue file:
```
FILE "WAR1.BIN" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 29:39:25
  TRACK 03 AUDIO
    INDEX 01 30:26:69
  TRACK 04 AUDIO
    INDEX 01 34:38:54
  TRACK 05 AUDIO
    INDEX 01 38:25:46
  TRACK 06 AUDIO
    INDEX 01 42:07:59
  TRACK 07 AUDIO
    INDEX 01 45:57:10
  TRACK 08 AUDIO
    INDEX 01 49:35:12
```
With this setup, crash happens in `CDROM_Interface_Image::ClearTracks()`:

```
void CDROM_Interface_Image::ClearTracks()
{
	for (auto &track : tracks) {
		if (track.file) {
			delete track.file;  // <- crash happens here
		}
	}
	tracks.clear();
}
```

Turns out in this case, multiple tracks point to the same TrackFile (`track.file` field) object (I'm not sure if this was intentional or not); all tracks try to destroy the same object on close.

@krcroft I think two scenarios in here might be happening, but I don't know the surrounding code well enough to decide:
- either TrackFile object is supposed to be shared between tracks (in such case `shared_ptr` might be a good solution here)
- or TrackFile is supposed to be owned by one specific object and Track objects should access file indirectly (so `unique_ptr` in owning object and mechanism to refer for indirect access).

What do you think?

**Comment by krcroft** [comment]
Glad you caught this, and wrote up such a detailed issue report.  The intent of the codec PR was to scope it to the per-file handling of CUE mounts, and subsequently to refinements upstream regarding the audio decoding and mixing.  In this case, the IMG mounting logic _should_ be intact.  Will poke around and report back!

**Comment by krcroft** [comment]
Both SVN and staging do: `Track &prev = *(tracks.end() - 1)` in `CDROM_Interface_Image::AddTrack`, so that's how we're getting duplicate `track.file` assignments for each `Track` object in the vector.  `end() - 1` is our leadout track, which is always a dummy.

SVN's destructor uses a temporary `TrackFile* last` variable to keep track of the currently deleted `track.file`, and only actually delete the next `track.file` if it's _**not**_ equal to last... so then it skips.

``` c++
	TrackFile* last = NULL;	
	while(i != end) {
		Track &curr = *i;
		if (curr.file != last) {
			delete curr.file;
			last = curr.file;
		}
		i++;
	}
```

Based on SVN's logic, the intent is to have duplicate `track.file` values (and only perform one actual delete).  So you're suggestion to use `shared_ptr` sounds like the best route.
