### ISSUE TITLE
Fix shortening of long filenames on PPC

### ISSUE THREAD

**Issue by kas1e** [dreamer/dosbox-staging#162]
Found today another bug in staging which didn't happen in the latest original DosBox.

Take as example ocp260pre6.zip filename. That what I have with staging:

http://kas1e.mikendezign.com/aos4/dosbox/longfilenames/dn_000.png

That what I have with the latest original DOSBox:

http://kas1e.mikendezign.com/aos4/dosbox/longfilenames/dn_001.png

See on the right panel, we have 2 files after the dirs. In original we have ocp260~.zip as expected, but in Staging, we have some cryptic numbers like ~7046798.zip.

But worth of check on other platforms IMHO as well.

**Comment by dreamer** [comment]
In dosbox-staging we fixed lots of  buffer overflow errors indicated by static code analysis, this might be a side-effect of one those.Thanks for testing, digging in :)

**Comment by dreamer** [comment]
The file shows up as `OCP260~1.ZIP` in Norton Commander and when listing directory via `DIR` (tested on Linux, x86_64). How does it look like when simply listing the dir? What program do you use in your screenshots?

**Comment by kas1e** [comment]
Same when I just do pure "DIR" command, without anything else, just pure DosBox's shell

**Comment by dreamer** [comment]
I think you can wait with tests for now. Some time ago we fixed buffer overflow bug, that could happen if the directory contains a huge number of files (e.g. more than vfat would handle - which is possible on practically any modern filesystem), and this seems to somehow be a side-effect of this change. I'm not sure how yet - if I won't be able to figure it out, then I'll post a branch for you to test.

**Comment by krcroft** [comment]
@kas1e ; you're a testing machine! Keep them coming :-)

**Comment by dreamer** [comment]
I am lost, I see nothing in this code that should behave differently on big endian…

@kas1e can you test the following branch: `po/shortname-investigation-1`? It will print some logs to stderr, I am interested in those.

Also, when testing I discovered new bug (in DOSBox, and also visible in dosbox-staging): when I have 3 files in local directory:
```
-rw-rw-r--. 1 dreamer_ dreamer_    0 Feb  4 20:19 ocp260pre5.zip
-rw-rw-r--. 1 dreamer_ dreamer_    0 Feb  4 16:38 ocp260pre6.zip
-rw-rw-r--. 1 dreamer_ dreamer_    0 Feb  4 19:56 ocp260pre7.zip
```

They will be named:
`ocp260pre5.zip` -> `OCP260~1.ZIP`
`ocp260pre6.zip` -> **`OCP260~3.ZIP`**
`ocp260pre7.zip` -> `OCP260~2.ZIP`
(based on modification time, not original file name). This seems terrible, as when a new file appears, all `~<num>` are relabelled (instead of being based on the original, long name).

Can you confirm the same problem is visible for you?

**Comment by kas1e** [comment]
> can you test the following branch: po/shortname-investigation-1? It will print some logs to stderr, I am interested in those.

Yes, sure. That what I do: I create a directory "d" in which put 3 files: ocp260pre5.zip, ocp260pre6.zip and ocp260pre7.zip. Then run DOSBox-staging, then ```mount c: d``` and the result are:

```
8/1.Work:dosbox> dosbox_staging 
DOSBox version git
Copyright 2002-2019 DOSBox Team, published under GNU GPL.
---
CONFIG: Loading primary settings from config file dosbox.conf
SDL:Current window pixel format: SDL_PIXELFORMAT_ARGB8888
SDL: Mouse will be captured after clicking and middle-clicks will be sent to the game.
MIXER: Got different values from SDL: freq 44100, blocksize 1024
No working midi device found/selected! Please check your settings and/or compilation environment.
MIDI: Opened device:none
One joystick reported, initializing with 4axis
create_short_name_id OCP260PRE5.ZIP
filelist_size 0
gcc_unlikely
short_nr 4712862442
strlen id 7
short_name (1) 
short_name (2) ~4294967
short_name (3) ~4294967.ZIP
create_short_name_id OCP260PRE6.ZIP
filelist_size 1
found low high cmp 0 1 0 0
compare_shortname 0 OCP260PRE6.ZIP ~4294967.ZIP
short_nr 9007829738
strlen id 7
short_name (1) 
short_name (2) ~4294967
short_name (3) ~4294967.ZIP
create_short_name_id OCP260PRE7.ZIP
filelist_size 2
found low high cmp 0 4294967297 0 1664451628
compare_shortname 0 OCP260PRE7.ZIP ~4294967.ZIP
short_nr 12884901934
strlen id 7
short_name (1) 
short_name (2) ~4294967
short_name (3) ~4294967.ZIP 
```

As a result, when I do "dir" I have 3 files with the same name:

```
~4294967.ZIP 
~4294967.ZIP 
~4294967.ZIP 
```

> Can you confirm the same problem is visible for you?

At least in the original DOSBox of r4293 I didn't see such problem. All that I do its copy the same file as you do with names 5,6,7 at the end, then after few seconds manually modify "pre6" one (so it has newer date of modification), and then mount them from some directory : and nope, in the DIR and in the DosNavigator all of them come as expected in the list: pre5 marked as 1, pre6 as 2 and pre7 as 3.

Then I tried to keep pre6 untouched (so have old modification date), and touch instead pre6 and pre7: and still no, all show fine. That at least with r4293

**Comment by krcroft** [comment]
It's unfortunately not reproducible on Linux/PPC :disappointed: 
![Screenshot_2020-02-04_13-18-46](https://user-images.githubusercontent.com/1557255/73788082-44c67000-4751-11ea-88f0-b740e470f39d.png)

**Comment by kas1e** [comment]
@krcroft 
I see from your screenshot, that you have for "short_nr" sane values, like 1,2,3, and shorname (1) always present. For me "short_nr" already some big value.

I assume there can be some ifdefs somewhere about Linux maybe? Or again that short/int/long type size differences.

**Comment by krcroft** [comment]
Absolutely @kas1e ; I was hoping to see the same interactions regarding the larger C++ container types (size_t's) intermingling with the smaller types (not due to the code, which looks good - but instead something wrong on the compiler/libc/stdc++ library side) all for the reasons you've suggested.. but unfortunately the numbers came out OK. 

The good news is the code it tight enough that this can probably be isolated down to a snippet of code, and provided upstream to either gcc or the library projects - where ever the bug might live.  And in the meantime, it would also highlight a general category of code or C++ constructs that will similarly fail and can be worked-around.

**Comment by dreamer** [comment]
The really troubling thing in here is this: there is literally no code between the log line printing `gcc_unlikely` and log line `short_nr 4712862442`. It's literally `return 1`. This might indicate some problem with GCC's `__builtin_expect`… it would be really bad if this turned out to be the case.

Please retest with new commit on branch `po/shortname-investigation-1`.

**Comment by kas1e** [comment]
@dreamer 
There output for new commit:

```
create_short_name_id OCP260PRE5.ZIP
filelist_size 0
returning 1
short_nr 4713572822
strlen id 7
short_name (1) 
short_name (2) ~4294967
short_name (3) ~4294967.ZIP
create_short_name_id OCP260PRE6.ZIP
filelist_size 1
found low high cmp 0 1 0 0
compare_shortname 0 OCP260PRE6.ZIP ~4294967.ZIP
short_nr 9008540118
strlen id 7
short_name (1) 
short_name (2) ~4294967
short_name (3) ~4294967.ZIP
create_short_name_id OCP260PRE7.ZIP
filelist_size 2
found low high cmp 0 4294967297 0 1623041244
compare_shortname 0 OCP260PRE7.ZIP ~4294967.ZIP
short_nr 12884901934
strlen id 7
short_name (1) 
short_name (2) ~4294967
short_name (3) ~4294967.ZIP
```

**Comment by dreamer** [comment]
OK, let's test if the problem lies either in coversion from `int` to `uintptr_t` or in printf-ing `PRIuPTR`… (both of these things differ dosbox-staging from upstream).

Test the latest commit on `po/shortname-investigation-1`, please (b41f8ab68709f87b3c67cb610d0581f617814788).

**Comment by kas1e** [comment]
@dreamer 
Wow! It works! Check this out:
http://kas1e.mikendezign.com/aos4/dosbox/longfilenames/longname_fixed.jpg

So... Have any idea wtf ?:) Just to know if it something need to be deal on our side in GCC port, or it just something in terms of type differences which need to be ifdefed in the DosBox?

**Comment by dreamer** [comment]
I'm afraid we might've uncovered a bug either in GCC/C++11 for AmigaOS or AmigaOS implementation of `snprintf` function… not sure yet - in the evening I'll prepare a set of small code snippets to help us identify the root cause. Thank you for testing - I think it'll be beneficial to all projects involved. :)

As for the fix in dosbox-staging - I'm glad it worked :) I'll clean it up and trigger a review; in all other cases we used `PRIuPTR` it was for logging or leaving a message in a case of critical error, so nothing game-breaking, but we'll need to review those uses anyway. Redefining Bitu alias is also an option - we'll see.

**Comment by krcroft** [comment]
That's a relief if it's only in `snprintf`.  The snippet will be excellent because it will let us flag it directly during configure (`#has_snprintf_priuptr_bug`), instead of a bunch of OS / architecture / and compiler checks in the code (`#if ppc, #ifndef linux #if gcc .. `)

**Comment by dreamer** [comment]
@kas1e Can you do quick re-test with `po/shortname-investigation-2` to confirm it's still working?

I prepared small testfile to confirm string formatting was the root cause here: https://gist.github.com/dreamer/27190792c165e4f9d19510e82f8a4d02

Compile it with `g++ -std=c++11test-priuptr.cpp`; I included few other less popular types (but not all).

**Comment by kas1e** [comment]
@dreamer 

> Can you do quick re-test with ```po/shortname-investigation-2``` to confirm it's still working?

Yes, everything fine! Thanks a bunch!

> I prepared small testfile to confirm string formatting was the root cause here:

Ok so, we have 2 "C" libs on amigaos4: clib2 and newlib. Both have + and -, and newlib is default in our SDK. So, with newlib build we have that:

```
9/0.Work:a> test-priuptr_newlib 
Error (%llu) "1" != "160630978006482943"
Error (%llu) "1" != "160630978006482943"
Error (%llu) "1" != "160630978006482943"
Error (%llu) "1" != "160630978006482943"
Error (%lld) "1" != "160630978006482943"
Error (%lld) "1" != "160630978006482943"
Error (%lld) "1" != "160630978006482943"
Error (%lld) "1" != "160630978006482943"
```

Then, if i build the same test case with clib2, then:

```
9/0.Work:a> test-priuptr_clib2 
Ok (%lu)
Error (%llu) "1" != "4294967296"
Error (%llu) "1" != "4294967296"
Error (%llu) "1" != "4294967296"
Ok (%ld)
Error (%lld) "1" != "4294967296"
Error (%lld) "1" != "4294967296"
Error (%lld) "1" != "4294967296"
```

Not sure what did it mean through :)  But when i run it on my Cygwin's x64 GCC, then all fine:

```
$ ./test-priuptr_x86.exe
Ok (%lu)
Ok (%lu)
Ok (%lu)
Ok (%lu)
Ok (%ld)
Ok (%ld)
Ok (%ld)
Ok (%ld)
```

So seems something very bad on our side happens?

**Comment by dreamer** [comment]
Hmm, I just found [this note](https://en.cppreference.com/w/cpp/types/integer#Notes):

> The C99 standard suggests that C++ implementations should not define the above limit, constant, or format macros unless the macros __STDC_LIMIT_MACROS, __STDC_CONSTANT_MACROS or __STDC_FORMAT_MACROS (respectively) are defined before including the relevant C header (stdint.h or inttypes.h). This recommendation was not adopted by any C++ standard and was removed in C11. However, some implementations (such as glibc 2.17) try to apply this rule, and it may be necessary to define the __STDC macros; C++ compilers may try to work around this by automatically defining them in some circumstances.

Hmm, let's test these macros out in our testcase; I just added them to the code snippet: https://gist.github.com/dreamer/27190792c165e4f9d19510e82f8a4d02

Otherwise, I think we should start with reporting these as bugs to both clib implementations - perhaps it'll be bumped to C++ compilers from there, let's see.

**Comment by kas1e** [comment]
With new test-case its still the same..

So, bug then called as "PRIu and PRId all broken"?

**Comment by dreamer** [comment]
Yeah, that's the gist; add me to CC, please (you can find my email in git log).

**Comment by kas1e** [comment]
@dreamer 
I have a mail from one of our developers, that what he say when i ask what happens:

```
Your test code has a problem where "int x" is 32-bit, but %llu/%lld needs a 64-bit value. The code might happen to work correctly on little-endian machines, provided that the next 32-bit value in memory happens to be 0. On big-endian machines like ours you're guaranteed to get a big number...

You should replace "int x" with "T x". T gets replaced with the template parameter (e.g., uintptr_t, uint64_t). Then the code should work.

%lu & %ld are for 32-bit values, which is why some clib2 tests are passing. Your results suggest that PRIuPTR is 32-bit for clib2 but 64-bit with newlib for some reason.
```

**Comment by dreamer** [comment]
Eh; yes a tweak is needed, sorry about that - but not the one that dev pointed out. In line 18:

> snprintf(buf_2, sizeof(buf_2), fmt, x);

Needs to be replaced with:

> snprintf(buf_2, sizeof(buf_2), fmt, y);

The intention is: buf_1 stores formatted int (formatted using %d), buf_2 stores T formatted using specific designer passed via parameter.

On LE it does not matter, of course.

**Comment by dreamer** [comment]
This issue was closed automatically by relevant commit landing in the master branch; we can continue discussing fixes libc projects in here, I think there's no need to create a tracking issue (unless it'll be more convenient for some reason).

**Comment by kas1e** [comment]
@dreamer 
Ok, with the last fix, clib2 tested all passes well and give "ok", but newlib ones fail on PRIuPTR and on PRIdPTR. Then one of the developers says that I use the older SDK of newlib, which contains broken inttypes.h. So once I replace it, all the tests pass fine.

Sorry that I take much of your time with it, while the issue, in general, was just me having older include for newlib (can't imagine before that such a bug can sleep on me, while I do loot of porting work with it).  But at least as i see it was cleaned a bit and fits better :)

Thanks again for all your help with big-endian things!

**Comment by dreamer** [comment]
@kas1e nothing to be sorry about, we improved dosbox-staging, confirmed what the issue was, and learned something along the way. Wins all around in my book :)
