### ISSUE TITLE
Regression in Tomb Raider 1 (Steam)

### ISSUE THREAD

**Issue by dreamer** [dreamer/dosbox-staging#201]
When merging in recent CD-DA changes I did quick tests using HoMM2 and it works fine, but I just discovered a regression in TR1; game starts ok, CD seems loaded (mp3 tracks 2-10 are logged on stdout), but then dosbox-staging hangs after the intro moves (I presume when trying to play mp3 menu music).

I ran git bisect and unfortunately couldn't arrive at specific commit, as several commits in the row were not compilable (probably small change was fixed in one of later commits); anyways, here's git bisect output:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c7eebacde9b5e6d1d7595ea873832d9d118ad26d
9bebfdabd351c5edb11690b65f19edbc9020f732
e8e9e0ef4f760ae0e9c936d5c59ad6ab8802d0c3
1393c1316c863ae8353098f92263a91cff60477d
cff1ded8e95bf5e6268d11963bf4fb5e096cdd62
c76cc09d97852591a6c018bab1e0d524504f6d17
We cannot bisect more!
```

Last known working version: 459f7d32f91872cbb1961d1ebb8abe9f5cd89ae5
First known broken version: c76cc09d97852591a6c018bab1e0d524504f6d17

I will try to pinpoint it more precisely, but in the meantime - @krcroft - can you try to reproduce the issue?

(edit)
I can't reproduce the issue when loading unrelated .cue with mp3s; but when I tried to play TR1 music using OCP it hung again; working on preparing the minimal testcase.

(edit2)
I managed to reproduce it without TR1, testcase is: load .cue with 2 mp3 tracks, play 2nd track using OCP.

dosbox-staging goes into infinite loop, debug logs:
```
CDROM: GetTrack at sector 9491 => track 2 [start 9491, end 24722]
CDROM: seek to 0 avoided with position-tracking
CDROM: Play sector 9491 to 24722 in track 2 [start 9491, end 24722], for 8955828 PCM frames at rate 44100
CDROM: GetTrack at sector 9491 => track 2 [start 9491, end 24722]
CDROM: seek to 0 avoided with position-tracking
CDROM: Play sector 9491 to 24722 in track 2 [start 9491, end 24722], for 8955828 PCM frames at rate 44100
CDROM: GetTrack at sector 9491 => track 2 [start 9491, end 24722]
CDROM: seek to 0 avoided with position-tracking
CDROM: Play sector 9491 to 24722 in track 2 [start 9491, end 24722], for 8955828 PCM frames at rate 44100
```

**Comment by krcroft** [comment]
Interesting; for mp3, the underlying track position is likely being left at the end-position after initially populating the track duration in ms. The most robust solution I think is to start our "position cache", value in cdrom.h `uint32_t  track_pos` as something invalid instead of 0. 

Right now it defaults to zero, which assumes the track is ready to decode from the beginning.  So if we initialize it with `uint32_t track_pos = -1`, this ensures that the first seek will be forced, and from that point on it will hold the actual underlying track decode position.

Is there a better way to set -1 to an unsigned value? (std::max<?>)

**Comment by dreamer** [comment]
e.g. `std::numeric_limits<uint32_t>::max()`

https://en.cppreference.com/w/cpp/types/numeric_limits/max

**Comment by krcroft** [comment]
This is also hilarious - but before I pushed the PR, I tested each codec, mono and stereo, at various bit-depths, on a couple of my machines.  But alas.. all of them start playing at a non-zero offset :-)  So no wonder I didn't catch this!

**Comment by krcroft** [comment]
Thanks for the `constexpr` max value @dreamer ; I prefer that over -1 or the hex value. PR in-bound.

Ideally we could "tell()" the position from the underlying track for our initial position, but that's not available in the SDL function-struct. Regarding initializing with the maximum value, we also have protection against the corner-case scenario where as DOS game also requests that we seek to `0xffffffff` because we check the user value with:  `assertm(requested_pos <= MAX_REDBOOK_BYTES, "Requested offset exceeds CDROM size");`
