### ISSUE TITLE
Different brightness levels in graphics text versus 0.74-3

### ISSUE THREAD

**Issue by datapackrat** [dreamer/dosbox-staging#207]
Trying dosbox-staging-windows-v0.75.0-pre-613-gf2029, I noticed that text in graphics mode are a different level of brightness than the same display in 0.74-3.

[side-by-side comparison](https://i.imgur.com/mo9kPiH.png)

Same program, running in VESA mode 101H, text via DOS calls. Graphics are direct memory writes.

Not sure which is "correct", but wanted to bring it to your attention.

**Comment by dreamer** [comment]
I'm not sure if it's really brightness, but rather a different colour altogether. dosbox-staging seems to be using default VGA text colour (light grey) while 0.74-3 uses white in this case for some reason. Maybe it's a bug in dosbox-staging - or maybe in SVN or 0.74-3 - I can't tell now.

Can you share the program you used here? I googled for DEBUG8 executable, but couldn't find anything. With program in hand I could bisect and find out which commit exactly introduced this difference. Perhaps someone could test on a real hardware as well.

**Comment by datapackrat** [comment]
Source (and compiler) and executable:  [DEBUG8](https://github.com/datapackrat/debug8)

**Comment by dreamer** [comment]
I tested DEBUG8 in dosemu - it shows the same behaviour as dosbox-staging. Git bisect points to this commit as reason of different behaviour: d2209e10b5d9b4a62feb75e9dc18d81e0d7a9630 (yup it's from 2015)

It seems like this was an intentional fix, but only made in SVN trunk, never ported to any of 0.74* releases.

Closing this report; if new facts will come up (maybe someone wants to run it on real hardware?), feel free to reopen it. Thank you! :)

**Comment by krcroft** [comment]
Awesome work bisecting that out!
