### ISSUE TITLE
Next workflow update (discussion)

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#65]
@dreamer , for the next revision to our workflow, you mentioned moving to `--enable-debug`.

Should we move to that across the board for all our CI jobs?  I _think_ we can, because the debug system rides on top of a fully-functioning DOSBox, so we're not giving up or excluding an "release" code-paths by enabling debug.

Also, I'm using these flags at home, which I find helpful: `-Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic`; so we can considering adding them too.

We might also want to consider going even further to this recommended set:
 https://github.com/lefticus/cppbestpractices/blob/master/02-Use_the_Tools_Available.md#gcc--clang

Some of them can be very helpful - however a handful only work with GCC 6 and greater.  So perhaps for our usual CI builds we would differentiate flags based on GCC 5.x vs 6+.

**Comment by dreamer** [comment]
> @dreamer , for the next revision to our workflow, you mentioned moving to `--enable-debug`.
> 
> Should we move to that across the board for all our CI jobs? I _think_ we can, because the debug system rides on top of a fully-functioning DOSBox, so we're not giving up or excluding an "release" code-paths by enabling debug.

I'm not sure… `--enable-debug` is first of many optional build configurations and I see no reason to treat it differently than `--disable-dynrec`, or `--disable-unaligned-memory`… And we probably shouldn't build all those optional configurations on every push.

Earlier I thought that turning on `--enable-debug` (damn, this flag really should be called `--enable-debugger` - it is confusing) should be used for debug jobs and disabled for dynamic analysis jobs and future release jobs, but I'm not so sure any more.

Perhaps a better way would be to have something like this:

- nigthly workflow that iterates through many, many different build configurations (perhaps on Linux only, not sure), with its own warning limits per-configuration (which we would occasionally update)
- when developing a larger change, developer could uncomment a line `# on: push` in that workflow, to trigger all those build configurations on demand (even if building all of them will take an hour or so - the build is on demand, so it won't be a problem)

Aside of 10 configuration flags, that are listed in INSTALL file, there are more (e.g. `--disable-screenshots`) and some build configurations that require users to comment/uncomment lines in code.

One more thing to remember about: we should test these configurations with different sets of packages installed, some examples:
- `--disable-screenshots` job should not have `libpng` installed
- A job without `SDL_net` installed is needed, to test if the dependency haven't switched from optional to mandatory
- `--enable-debug` requires some kind of curses library, but our normal jobs should be buildable without curses lib

> Also, I'm using these flags at home, which I find helpful: `-Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic`; so we can considering adding them too.
> 
> We might also want to consider going even further to this recommended set:
> https://github.com/lefticus/cppbestpractices/blob/master/02-Use_the_Tools_Available.md#gcc--clang
> 
> Some of them can be very helpful - however a handful only work with GCC 6 and greater. So perhaps for our usual CI builds we would differentiate flags based on GCC 5.x vs 6+.

I was bitten by "unstable" `-Wextra` warnings in the past (IIRC they appeared/disappeared with minor compiler updates), but that was in times of transition from GCC 4.x to GCC 5.x. I find those warnings a bit too pedantic sometimes - but haven't tried them in DOSBox yet.

`-pedantic` - I am against. New GCC and Clang compilers sometimes offer very useful extensions and I don't want to encourage devs to removing them just to bring compilation closer to ISO C++ limitations.

`-Wshadow -Wnon-virtual-dtor` (or maybe even `-Weffc++`?). These warnings encroach more on "coding style" area, and not merely a machine warning us "hey, there might be a bug in here". But I like them… we should probably group them separately when summarizing warnings?

Also, one small thing… I find colourized output from GCC and Clang very useful on my local compilation… but for our logs it might be too much. What's your opinion on moving our CI jobs back to non-colourized output?

**Comment by LowLevelMahn** [comment]
would be great to have one of the Free/CI Code Coverage Analysis Tools integrated (for example: https://codecov.io/) - to get a feeling what the sanitizers can reach

**Comment by krcroft** [comment]
Regarding colorized output: I can't image anyone /not/ wanting colorized output - and I appreciate that GitHub correctly renders color in it's web UI.  Unfortunately though, the web UI also prevents searching for strings in the entire log, and limits the search to the little window of text currently on the screen:

![2019-12-01_12-33](https://user-images.githubusercontent.com/1557255/69919938-1b2e5700-1437-11ea-897c-43dd32456710.png)

This means that to find something, I have to scroll through thousands of lines and hunt with my eyes. Usually I give up and fallback to the "raw log", and perform the search inside the despite the color symbols being hard to deal with.  

Based on my use and GitHub's limitations, I would prefer not to have color in our logs.

**Comment by krcroft** [comment]
Reporting back after a bit of progress.. here's a workflow I called the _Configuration gauntlet_ that tries to hit all the `./configure` options and optional libraries:

https://github.com/dreamer/dosbox-staging/runs/328630080
![2019-12-02_16-46](https://user-images.githubusercontent.com/1557255/70006836-5443f580-1523-11ea-8d2c-275dfe76224f.png)

I previously had runs without `zlib` and `libpng` (separately), but `SDL` depends on both of those - so as soon as you remove either of them, `apt-get` tears down all of SDL along with pile of other pretty low-level libraries.  So in theory DOSBox might not use these (if it can't find the headers or libs), but unless someone is willing to compile a large part of their system without these (or statically link them), then these two are effectively secondary dependencies.

As for choosing warning flags, I threw the kitchen sink these these for fun to see what we get. 
It's actually pretty enlightening:
``` txt
2019-12-02T23:51:45.7506161Z Warnings grouped by type:
2019-12-02T23:51:45.7506698Z 
2019-12-02T23:51:45.7507035Z   effc++                  : 3875
2019-12-02T23:51:45.7507991Z   useless-cast            : 893
2019-12-02T23:51:45.7508399Z   format=                 : 343
2019-12-02T23:51:45.7508930Z   unused-parameter        : 334
2019-12-02T23:51:45.7509493Z   implicit-fallthrough=   : 92
2019-12-02T23:51:45.7509853Z   switch                  : 85
2019-12-02T23:51:45.7510359Z   double-promotion        : 80
2019-12-02T23:51:45.7515473Z   shadow                  : 80
2019-12-02T23:51:45.7515920Z   maybe-uninitialized     : 71
2019-12-02T23:51:45.7516152Z   pedantic                : 50
2019-12-02T23:51:45.7516468Z   unused-function         : 35
2019-12-02T23:51:45.7516761Z   sign-compare            : 14
2019-12-02T23:51:45.7517053Z   unused-result           : 14
2019-12-02T23:51:45.7517346Z   non-virtual-dtor        : 12
2019-12-02T23:51:45.7517641Z   ignored-qualifiers      : 7
2019-12-02T23:51:45.7517778Z   reorder                 : 6
2019-12-02T23:51:45.7518066Z   format-nonliteral       : 5
2019-12-02T23:51:45.7518356Z   unused-but-set-variable : 5
2019-12-02T23:51:45.7518647Z   empty-body              : 5
2019-12-02T23:51:45.7518935Z   unused-variable         : 2
2019-12-02T23:51:45.7519222Z   duplicated-branches     : 2
2019-12-02T23:51:45.7519514Z   int-in-bool-context     : 2
2019-12-02T23:51:45.7519790Z   misleading-indentation  : 1
2019-12-02T23:51:45.7519878Z 
2019-12-02T23:51:45.7520014Z Total: 6013 warnings (out of 6013 allowed)
```
Effective C++ dwarfs the rest, but I find most of its suggestions have very real consequences if not adhered to.   

For example, if you have a class with raw pointer members, it warns if you don't also define a copy function or assignment operator - because without these the pointer values are simply copied into the assigned class, and now you have two two instances pointing to the same memory region, which will definitely lead to a double free in the instances that destructs last.  So I find these super-helpful; it's like have a C++ expert over your shoulder that you can ignore without any harm :-)

The other benefit is that the vast majority of those 3000+ warnings are coming from the same couple classes in DOSBox that are used everywhere - so one we clean those up with some `unique_ptr` and STL containers, we should see the count massively drop. 

As for the others - I think they're reasonable and helpful too. The useless casts are especially interesting beacuse that helps make our code more readable, especially if we can eliminate them as opposed to further bulking the code with ugly `static_cast<TYPE>(value)`s. 

`Pedantic` is another on that I think we shouldn't throw out too soon.  It's relatively mute (having only 50 warnings), and it's only provided helpful suggestions in my own C++ audio code; and certainly hasn't prevented me from using any modern C++11 constructs.  I suspect it's matured quite a bit since the early days of GCC 2.x to 4.x (which was also also a time when I found it to be excessively verbose). 

Anyway - all food for thought! Dig in, 🥙 🥗 🍺

**Comment by LowLevelMahn** [comment]
what about self building third parties like: zlib/libpng/SDL/SDL_net, i always build these under windows myself - also using mercurial head of SDL/SDL_net etc. (sometimes reduces warnings)

**Comment by krcroft** [comment]
For this "test-every-angle" that `./configure` allows, I'm not sure building 3rd party code hits any different pathways in the code, besides finer control to snip out `libpng` and `zlib` (if we really care about those build cases). 

For delivering static release builds, pulling and building 3rd party source sounds good. That would go in a different workflow yaml, says `releases.yml`, in which we could generate one or perhaps two binaries at-most for each supported system. 

- Linux: 64-bit static, 64-bit dynamic (bundled with libs and a launcher to LD_LIBRARY_PATH them in?)
- macOS: 64-bit static, 64-bit dynamic (bundled with libs?)
- Windows: 32-bit static, 64-bit static (any value in dynamic? User would need `vcpkg` or `msys2 + pacman`)

**Comment by dreamer** [comment]
@krcroft Oh, wow - I expected some `effc++` warnings, but not thousands of them. I think this will be extremely useful… even if somewhat intimidating at first.

Regarding zlib (and consequently, libpng) - I agree - we don't need to push water uphill with a rake just to prove a point.

I will dig in to see what other warnings are in there. As for now, I don't have strong opinions on how to integrate it into our workflow. I would be ok with just enabling it as-is for nightly builds, but as part of the review, it might be too much. Not sure though - I will dig in the kind of warnings, that are reported and make up my mind after that.

> what about self building third parties like: zlib/libpng/SDL/SDL_net, 

@LowLevelMahn For normal development work, I suggest using either vcpkg or MSYS2 - it's much faster, easier, and less error-prone this way. It's a shame MinGW does not come with a serious package manager of its own :(.

Officially managing build process for 3-rd party shared libraries is an undue maintenance burden, I would rather not commit to - but if you have some stellar scripts or makefiles, that provide value for very specific use-cases - feel free to send them as PRs - directory `contrib` was created exactly with things like this in mind :).

The easiest way to build on Windows right now is to use Visual Studio 2019 (it's free to use) + vcpkg (it's open source, popular, Microsoft-backed, free repository of C/C++ libraries). Build instructions are in README.md file :). You can't use this approach with SVN though, as upstream ships non-functional solution files because they want to be compatible with some old, deprecated version of VS. I have literally no way of obtaining that old versions of VS, so all solution-related changes live only in dosbox-staging.

The build process on Windows would be even easier without autotools… - e.g. vcpkg integrates natively with CMake, so that would enable easy MinGW-based builds, without rebuilding the world. But that's the story for another time.

**Comment by krcroft** [comment]
> f you have some stellar scripts or makefiles, that provide value for very specific use-cases - feel free to send them as PRs - directory contrib was created exactly with things like this in mind :).

Great suggestion! @LowLevelMahn ,  we recently added a static-Opus-builder makefile.  Similar makefile(s) could be made for the other libs; feel free to use and copy if you can `contrib`ute :-)

**Comment by krcroft** [comment]
> I would be ok with just enabling it as-is for nightly builds, but as part of the review, it might be too much. 

Yeah - it's a toss up; on one hand, a gargantuan number of warnings feels like too much to wade through (I found with search, I can quickly narrow down to the block of warnings against my own `.cpp` and ignore those pulled in from the other headers). 

The value is to the person writing the code.. if their new code would throw up a bunch of new effc++ warnings, they probably would want to know and fix them.  It would also be unfortunate to merge a big chunk of changes, only to see a pile of new effc++ warnings show up against it once they hit master (and the nightly job grinds through it).

Another option would be to pipe them off to a separate file, as opposed to touching stdout, so it makes reading the push CI more do-able.

**Comment by LowLevelMahn** [comment]
> The easiest way to build on Windows right now is to use Visual Studio 2019 (it's free to use) + vcpkg (it's open source, popular, Microsoft-backed, free repository of C/C++ libraries). Build instructions are in README.md file :). You can't use this approach with SVN though, as upstream ships non-functional solution files because they want to be compatible with some old, deprecated version of VS.

im building svn (dosbox heavy with all dependencies self build) using VS2010/2015/2017 - currently got no  VS2019 - but manually, no CMake/or scripts involved

>  I have literally no way of obtaining that old versions of VS, so all solution-related changes live only in dosbox-staging.

here you can get VS2015/17 as community edition for free
https://visualstudio.microsoft.com/de/vs/older-downloads/

**Comment by krcroft** [comment]
Apparently the effc++ warnings were modelled after Scott Meyer's famous book, Effective Modern C++: 42 Specific Ways to Improve Your Use of C++11 and C++14  (96% positive ratings, 5/5 stars). 

Also has written other high-calibre C++ book: https://www.aristeia.com/books.html: very impressive bibliograph, combined with that haircut smashes him through to level 11 on the alpha-geek scale.

**Comment by dreamer** [comment]
> For delivering static release builds, pulling and building 3rd party source sounds good.

- For Windows, I think we might get away with bundling .dll from vcpkg packages - but I don't know yet. 
- For Linux, it depends if SDL(2) and has a stable/versioned ABI provided across the distros. libpng does, opus does (we would just need to leave clear instructions about what packages to install and it would be fine). Aside of automatic release builds / tarballs:
  - We already have potential NixOS packager
  - I can work on copr/rpm until dosbox-staging gets into the repos (I'll need to do it anyway for Boxtron, and covering dosbox-staging at the same time would make my life easier)
  - Arch users are usually quite eager to put new things in AUR
- For macOS - I have no idea about good practices for creating macOS bundles. I saw some discussions on Vogons indicating, that current bundles are buggy. I don't even know how to re-create them at the moment :/

> That would go in a different workflow yaml, says `releases.yml`, in which we could generate one or perhaps two binaries at-most for each supported system.

I was experimenting with this in other repo. It would be somewhat confusing to users due to GitHub UI :( For now I concluded, that most user-friendly option would be to add a separate "Release" build in `linux.yml`/`macos.yml`/`windows.yml` - this way user who only skimmed through README.md without really reading it could find a way to release builds anyway. Maybe some better solution is there, though.

> Assume all release builds are maximally optimized: Ofast or O3, LTO and FDO, optimized for a semi-outdated but still 64-bit architecture (say, Core2 and newer), and stripped.

+1 

Except I think we might prefer to avoid Ofast, because:

`man gcc` says:
> -Ofast (…) It also enables optimizations that are not valid for all standard-compliant programs.

> If users/testers hit issues, we would probably ask for an issue submission with details how to reproduce, so we can dig into it dev-side (as opposed to sending them debug builds, instructions how to setup GDB and so on -- although no harm in keen users digging into that themselves and sending those details)

Yup :) The first, tiny, step towards reproducible reports was done already - version field is now long enough to show string generated before compilation via git-describe:

    $ git describe
    v0.75.0-pre-190-g15ca6691

This will provide clear-cut communication with testers (without second-guessing what version of code are they actually testing). I decided to name default tag `v0.75.0-pre` to be [semver](https://semver.org/)-compatible:

- `pre` means pre-release
- `190` is the number of commits since the tag was created (tag points at first commit where histories of dosbox-staging and SVN were merged on master) - it is human-readable way of providing hint if the build is "newer" or "older"
- `g15ca6691` indicates Git commit  15ca6691

**Comment by krcroft** [comment]
Thumbs up to all of it! I 
I can work on an Ubuntu PPA (until Debian/Ubuntu adds dosbox-staging into the baseline repos).

**Comment by krcroft** [comment]
> I can work on an Ubuntu PPA (until Debian/Ubuntu adds dosbox-staging into the baseline repos).

This is going extremely poorly.  I've jumped through the following hoops so far:
 - created an Ubuntu One account
 - Used my RSA key to sign their developer code of conduct
 - Approved to post PPAs
 - Created the necessary tree of files under the required `./debian` directory
 - Modified them so they work

However the actual build and submission process is not-trivial requires a lot of steps, signing files with your key, and so on.  Even though I'm an Ubuntu and Debian user, I'm baffled at how fragile, dated, and excessively cumbersome it all is.

Because of such a bad experience, I'm reluctant to put more time into it, and would rather focus on our cross-Linux-compatible tarball, which is beautify and simple to create.

**Comment by krcroft** [comment]
Suggest we close this issue and (if needed) open new issues for specific needs.
