### ISSUE TITLE
Mounting a floppy prevents dosbox-staging from clean exit

### ISSUE THREAD

**Issue by dreamer** [dreamer/dosbox-staging#94]
I was experimenting with fixing some code related to labelling floppy drives (because it does not work in DOSBox at all - seems like it got broken years ago), and noticed that dosbox-staging does not exit cleanly any more (I need to press ctrl-c to abort the process after exit).

Eventually, I pinpointed the smallest number of steps needed to trigger the regression:

    ./src/dosbox -c 'imgmount A ~/.dosbox/A/Disk01.img -t floppy' -c 'exit'

In my case, the image is the first floppy of Windows 3.11 installation disks, but presumably, it'll happen with other images as well.

git-bisect points to c9198b29446abc7b866bf4f607feaf3e7cbe1597 as a commit, that introduced the regression. I gave it a brief look (again, I reviewed this code in the past) and can't immediately spot the problem.

@krcroft Can you confirm this is actually an issue? Maybe it's something different related to my setup (or my floppy image).

The good thing about this bug: it forced me to use git bisect for the first time in a long time, and it gave me idea about how to do some preliminary regression setup.

**Comment by krcroft** [comment]
@dreamer , amazing work in bisecting the issue! Will dig into it, and trying to see what's going on. 

Definitely the code was meant to be as close to a one-one replacement as possible, but perhaps the RAII ownership handover between safe containers is not what the original code expects/relies on.  Just a guess though.

**Comment by krcroft** [comment]
The hang happens in `imageDisk`'s destructor when it tries to `fclose` a bogus `FILE` pointer.  

If you `imgmount a floppy.img -t floppy`, then one call to imageDisk's constructor occurs, which I've instrumented with a print statement:
```
src/ints/bios_disk.cpp:203 constructing imageDisk(floppy.img, 0x5555588daf00, ...)
```
However, unmounting it,  `mount -u a`, results in destruction of two `imageDisk` objects, both referring to `floppy.img` however the second `FILE*` is bogus and causing fclose to hang.
I've also added a print statement in the destructor:
```
include/bios_disk.h:63, ~imageDisk() destroying floppy.img, 0x5555588daf00
include/bios_disk.h:63, ~imageDisk() destroying floppy.img, 0x5555588b7010
```

Given I've disabled `imageDisk`'s copy operator, assignment operator, and default constructor, I'm not sure how a "second" imageDisk object is being created without its constructor being called (and a second constructor print statement doesn't happen), but I get two destructs. 

In the SVN code, the `fatDrive` class has `imageDisk* loadedDrive` member which gets leaked (without `fclose()` being called on it) because `fatDrive` does not have a destructor.   After this PR, that pointer became a `unique_ptr<imageDisk>`, which always destructs on termination.

To help debug this, I have a batch file:
```
imgmount a floppy.img -t floppy
mount -u a
```
I launch this directly or via gdb's `run` line. 

Feel free to checkout `kc/debug-imagedisk-2`, where I've added those output lines.  
Baffled so far.. insight very much welcome!

**Comment by krcroft** [comment]
A "splice" occurs to happen `src/dos/dos_programs.cpp` line 1406:
```
                case 1:
                    if (!((fatDrive *)newdrive)->loadedDisk->hardDrive) {
                        imageDiskList[drive - 'A'].reset(((fatDrive *)newdrive)->loadedDisk.get());
```
- `imageDiskList` is an array of `unique_ptr`'s, so on the reset it takes ownership to delete.
-  `newdrive->loadedDisk` is also a `unique_ptr` so it's also responsible for deleting.

However, in the above call we're using `.get()` to pass a pointer and not release ownership. However, if I release ownership, `newdrive->loadedDisk.release()`, then `newdrive->loadedDisk` becomes `nullptr` and the code doesn't work at that point.

**Comment by krcroft** [comment]
Here's one way to solve it:
https://github.com/dreamer/dosbox-staging/compare/kc/debug-imagedisk-3

@dreamer , do you know of any more elegant or STL-objects that start out responsible-owners, but then can "give up ownership", but still keep their pointer to passively use? (like we're doing here).

**Comment by dreamer** [comment]
> @dreamer , do you know of a better way to do this, or maybe there's an STL class that permits this type of "own-then-dont-own-but-still-use" behavior?

I haven't read into details of your investigation yet, but C++11 STL provides this either via 2 `shared_ptr`s or  a `shared_ptr`+`weak_ptr`.

**Comment by krcroft** [comment]
Swap fully swaps the content and ownerships of two values across two unique_ptr's, A becomes B, and B becomes A, without the need for the user to setup a temporary variable. 

We need two copies of A, and to hand over delete responsibility; or more specifically we only want one delete called on the value across our multiple containers.

Shared pointed looks like a great fit; will give this a try tomorrow! thanks for the pointer :wink:

**Comment by krcroft** [comment]
Swap fully swaps the content and ownerships of two values across two unique_ptr's, A becomes B, and B becomes A, without the need for the user to setup a temporary variable. 

We need two copies of A, and to hand over delete responsibility; or more specifically we only want one delete called on the value across our multiple containers.

Shared pointed looks like a great fit; will give this a try tomorrow! thanks for the pointer :wink:

**Comment by dreamer** [comment]
> Swap fully swaps the content and ownerships of two values across two unique_ptr's, A becomes B, and B becomes A, without the need for the user to setup a temporary variable.

Yup. This also means that when one of `unique_ptr`s holds a `nullptr`, then ownership was safely transferred :) (I believe it is the case here - newDrive being only a temporary object (but I don't know the full context - if newDrive still does something meaningfull with the pointed object after transfer, then `shared_ptr` will be better.

**Comment by krcroft** [comment]
A bit of fruitless progress; I trying switching from my "manual ownership/release" code over from all `unique_ptr` to `shared_ptr`, and git rid of my couple functions to keep track of `loadedDrive`'s ownership...  and hit double-free's everywhere.  

I had assumed that `shared_ptr` keep track of the all the references and only free on the last one. But maybe the way this code works it confuses it or we wind up with copies that each start having their own reference. I'm not sure.. my head is spinning after many hours of wrestling with it.

**Comment by krcroft** [comment]
Here are the key stakeholder objects for us to think about:

1. **imgDisks** is vector of polymorphic raw `DOS_Drive` pointers
1. **fatDrive** is derived from `DOS_Drive`, has a raw point `loadedDisk` of type `imageDrive` pointer
1. **imageDiskList** is an array of `unique_ptr<imageDrive>`

The action happens around `src/dos/dos_programs.cpp:1400`, where an **imgDisks** element is  dynamic-cast to a **fatDrive**, and its raw pointer `loadedDisk` member (an `imageDrive` object) is provided to **imageDiskList**.

After this operation, the code expects both **imgDisks** and **imageDiskList** hold the same (or pointers to) the same underlying `imageDrive` objects; and to prevent lock up only one call to a given destructor must be performed. 

So this is where we can choose what type of containers we want to use for these underlying types.
- imgDisks could use shared_ptr instead of raw pointers
- fatDrive class could use a shared_ptr for it's loadedDisks member instead of a raw point
- imageDiskList could be comprised of shared_ptr's instead of unique_ptrs

(I tried all of that - thinking they could take care of the problem "for free" via reference coulding down).. but hit double frees.. so gave up)

**Comment by dreamer** [comment]
@krcroft I did small follow up using all the info you gathered and tested few things:

1) The repeated commits above were my attempts at writing an automatic test for this issue. Unfortunately, my script kept working consistently on my computer, but on CI the results were random :( About 20-30% of time DOSBox just exited normally and issue did not appear.
2) One part of an issue was copying of raw pointer from one unique_ptr to another in `dos_programs`:

        imageDiskList[drive - 'A'].reset(((fatDrive *)newdrive)->loadedDisk.get());

    Fixing this line prevents double-free, but breaks the floppy mounts (they mount correctly, but display garbage).
3) Using `shared_ptr` actually fixed the issue, but more testing is needed (so far I tested with one floppy only, need to test what happens when multiple images are passed to single IMGMOUNT command or other types of images are mounted). See: 4d304a8b893f49de34e6507d1e7cbedc81005776

About #96 - it works, but I'm not sure if this is the best way forward. I think that if we'll manage to make `shared_ptr` work correctly in here, then some tricky code for hot-swapping the images using CTRL-F4 could be simplified.

**Comment by krcroft** [comment]
Using shared pointers exclusively is safer than mixing raw pointers with unique pointers, plus it simplifies the code; so win-win in my books too.
Will test it out on my side.
Very interesting how the CI machine doesn't reliably reproduce the error.  I like the test addition too; we can build up more cases using that structure.

**Comment by krcroft** [comment]
@dreamer , commit 4d304a8 is running clean on my side. Tested single `imgmount` & `mount -u`, multiple `imgmount`s (A, B, D, E) both with and without terminating `mount -u`, also tried variations with multiple disks + switching (ctrl+F4) and confirmed contents matched the images. PR it!

**Comment by dreamer** [comment]
I was reviewing surrounding code, wasted some time in the process (because bad variable naming lead me to investigating the wrong thing :/), but I think I found a related regression.

Regression seems to be triggered by [boot](https://www.dosbox.com/wiki/BOOT) command, when loading a single floppy.

I think I'll include my example test from earlier with the PR, but without CI part - we need to start documenting thing we test somehow.

**Comment by krcroft** [comment]
Excellent work catching this second regression.  It's good to know that both involved needing duplicate pointers in two (or more?) places.

Absolutely agree on the testing approach; for the next revision, I'll open a new issue first and lay down the proposed tests.
